name: provision

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-10.15
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run vagrant up
        run: vagrant up

